// <auto-generated />
using System;
using ApiAspnet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAspnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421014731_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("ApiAspnet.Models.Colonia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Habitantes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Colonias");
                });

            modelBuilder.Entity("ApiAspnet.Models.DetalleDiario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Autonomia")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CantidadBasuraKg")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CapacidadDiesel")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Diesel_Final")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Diesel_Recargado")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Diesel_inicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_TerminoEstimado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_TerminoReal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_orden")
                        .HasColumnType("TEXT");

                    b.Property<int>("ID_Ruta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ID_Unidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroTurno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Puches")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("km_Recorridos")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ID_Ruta");

                    b.HasIndex("ID_Unidad");

                    b.ToTable("Folios");
                });

            modelBuilder.Entity("ApiAspnet.Models.Empleado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DetalleDiarioID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isChofer")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("DetalleDiarioID");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("ApiAspnet.Models.Ruta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KM_Estimados")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Rutas");
                });

            modelBuilder.Entity("ApiAspnet.Models.RutaDetalleColonia", b =>
                {
                    b.Property<int>("ID_Ruta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ID_Colonia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PorcentajeAtendidos")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID_Ruta", "ID_Colonia");

                    b.HasIndex("ID_Colonia");

                    b.ToTable("RutaDetalleColonia");
                });

            modelBuilder.Entity("ApiAspnet.Models.Tipo_Unidad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LtrsDieselTanque")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Tipos_Unidades");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            LtrsDieselTanque = 0m,
                            Nombre = "volteo"
                        },
                        new
                        {
                            ID = 2,
                            LtrsDieselTanque = 0m,
                            Nombre = "redilas 12 de marzo"
                        },
                        new
                        {
                            ID = 3,
                            LtrsDieselTanque = 0m,
                            Nombre = "compactadores trisa"
                        });
                });

            modelBuilder.Entity("ApiAspnet.Models.Unidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ID_TipoUnidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ID_TipoUnidad");

                    b.ToTable("Unidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ID_TipoUnidad = 1,
                            Nombre = "1"
                        },
                        new
                        {
                            Id = 2,
                            ID_TipoUnidad = 1,
                            Nombre = "2"
                        },
                        new
                        {
                            Id = 3,
                            ID_TipoUnidad = 1,
                            Nombre = "3"
                        },
                        new
                        {
                            Id = 4,
                            ID_TipoUnidad = 2,
                            Nombre = "4"
                        },
                        new
                        {
                            Id = 5,
                            ID_TipoUnidad = 2,
                            Nombre = "5"
                        },
                        new
                        {
                            Id = 6,
                            ID_TipoUnidad = 2,
                            Nombre = "6"
                        },
                        new
                        {
                            Id = 7,
                            ID_TipoUnidad = 2,
                            Nombre = "7"
                        },
                        new
                        {
                            Id = 8,
                            ID_TipoUnidad = 3,
                            Nombre = "8"
                        },
                        new
                        {
                            Id = 9,
                            ID_TipoUnidad = 3,
                            Nombre = "9"
                        },
                        new
                        {
                            Id = 10,
                            ID_TipoUnidad = 3,
                            Nombre = "10"
                        });
                });

            modelBuilder.Entity("ApiAspnet.Models.DetalleDiario", b =>
                {
                    b.HasOne("ApiAspnet.Models.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("ID_Ruta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiAspnet.Models.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("ID_Unidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruta");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("ApiAspnet.Models.Empleado", b =>
                {
                    b.HasOne("ApiAspnet.Models.DetalleDiario", null)
                        .WithMany("Empleados")
                        .HasForeignKey("DetalleDiarioID");
                });

            modelBuilder.Entity("ApiAspnet.Models.RutaDetalleColonia", b =>
                {
                    b.HasOne("ApiAspnet.Models.Colonia", "Colonia")
                        .WithMany()
                        .HasForeignKey("ID_Colonia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiAspnet.Models.Ruta", "Ruta")
                        .WithMany("CoberturaColonias")
                        .HasForeignKey("ID_Ruta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colonia");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("ApiAspnet.Models.Unidad", b =>
                {
                    b.HasOne("ApiAspnet.Models.Tipo_Unidad", "TipoUnidad")
                        .WithMany()
                        .HasForeignKey("ID_TipoUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUnidad");
                });

            modelBuilder.Entity("ApiAspnet.Models.DetalleDiario", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ApiAspnet.Models.Ruta", b =>
                {
                    b.Navigation("CoberturaColonias");
                });
#pragma warning restore 612, 618
        }
    }
}
