// <auto-generated />
using System;
using ApiAspnet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAspnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415230429_Prueba1")]
    partial class Prueba1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("BlazorServer.Models.Chofer", b =>
                {
                    b.Property<int>("id_chofer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_chofer");

                    b.ToTable("Choferes");
                });

            modelBuilder.Entity("BlazorServer.Models.Colonia", b =>
                {
                    b.Property<int>("id_colonia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Habitantes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Km_carretera")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_colonia");

                    b.ToTable("Colonias");
                });

            modelBuilder.Entity("BlazorServer.Models.Despachador", b =>
                {
                    b.Property<int>("id_despachador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_despachador");

                    b.ToTable("Despachadores");
                });

            modelBuilder.Entity("BlazorServer.Models.Folio", b =>
                {
                    b.Property<int>("Id_Folio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Diesel_Final")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Diesel_cargado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Diesel_inicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Diesel_unidad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_captura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_orden")
                        .HasColumnType("TEXT");

                    b.Property<int>("Turno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_chofer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_despachador")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_ruta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_tipo_unidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_unidadcantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("km_regreso")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("km_salir")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("puches")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Folio");

                    b.ToTable("Folios");
                });

            modelBuilder.Entity("BlazorServer.Models.Folio_Detalle_Colonia", b =>
                {
                    b.Property<int>("id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Km_Limpiados_En_Este_Folio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Porcentaje_Alcanzado_En_Este_Folio")
                        .HasColumnType("TEXT");

                    b.Property<int>("id_colonia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_folio")
                        .HasColumnType("INTEGER");

                    b.HasKey("id_detalle");

                    b.ToTable("Folio_Detalles");
                });

            modelBuilder.Entity("BlazorServer.Models.Tipo_Unidad", b =>
                {
                    b.Property<int>("id_tipo_unidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_tipo_unidad");

                    b.ToTable("Tipos_Unidades");
                });

            modelBuilder.Entity("BlazorServer.Models.Unidad", b =>
                {
                    b.Property<int>("id_unidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_Unidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("id_tipo_unidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("id_unidad");

                    b.HasIndex("id_tipo_unidad");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("BlazorServer.Models.Unidad", b =>
                {
                    b.HasOne("BlazorServer.Models.Tipo_Unidad", "TipoUnidadInfo")
                        .WithMany()
                        .HasForeignKey("id_tipo_unidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUnidadInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
